### ISSUE TITLE
Header of Resume.

### ISSUE THREAD

**Issue by vinaysomawat** [vinaysomawat/Resume-Builder#3]
Change the header (Student Name, and delete the college logo).
Make it like this...
![header of cv](https://user-images.githubusercontent.com/30196269/52067941-a9307b80-25a1-11e9-98f5-684a2d0c39ed.png)

**Comment by ReenaSingh07** [comment]
can i help you?

**Comment by vinaysomawat** [comment]
Yes!

**Comment by Shian009** [comment]
i made the header as u wanted nd also created a pull request.

**Comment by vinaysomawat** [comment]
Pull Request merge in master branch.

**Comment by vinaysomawat** [comment]
[Pull request ](https://github.com/vinaysomawat/Resume-Builder/pull/6) is merged in master branch.
