### ISSUE TITLE
Create formal letter template

### ISSUE THREAD

**Issue by vinaysomawat** [vinaysomawat/Resume-Builder#7]
Write HTML/CSS code to generate formal letter template as shown in picture below.
![formal](https://user-images.githubusercontent.com/30196269/59704632-3c4d1380-921a-11e9-84a2-fc9d397fc022.jpeg)

**Comment by Rockdeldiablo** [comment]
Hi Vinay, I am a new user, I am currently trying to learn to use git and html.  Ii tried to solve the  issue I have already forked the repo, cloned it in my local machine. i have created a folder with 2 files (letter.html and letter.css) that generate the kind of output you seek but  even if on screen the file looks good i don't know how to force the printer to respect the margin area. i tried  with @media print but the printer has to shrink the file to fit the page anyway.

**Comment by vinaysomawat** [comment]
Being a beginner, you can copy the index.html file and edit it according to the solution.

Also, I create one solution, I am pushing the code. you can take reference.
![Screenshot from 2019-06-23 13-44-32](https://user-images.githubusercontent.com/30196269/59973398-1aa6b000-95bd-11e9-8b4a-261a5e77da69.png)

**Comment by Rockdeldiablo** [comment]
ah ok ok i saw you added the files. i forgot i had to send the pull request  to send them to your repo haha. git is not as easy as i thought

**Comment by Rockdeldiablo** [comment]
sorry vinay, i don't want to bother you any longer but now github now says that my fork is 2 commit ahead of yours when i have just synched the whole thing with git fetch upstream  and then git merge upstream/master. did i do something wrong?

**Comment by vinaysomawat** [comment]
I am closing this issue.
